-- Minimal faithful schema for isolated execution of the security regression.
-- Production data is never copied into this fixture.

create schema auth;
create schema private;
create schema extensions;

create extension pgcrypto with schema extensions;

create type public.record_status as enum ('active', 'blocked', 'archived');
create type public.property_status as enum (
  'onboarding', 'active', 'maintenance', 'blocked', 'offboarding', 'archived'
);
create type public.app_role as enum ('root', 'admin', 'owner', 'employee', 'tenant');

create role anon nologin;
create role authenticated nologin;

create table auth.users (
  id uuid primary key
);

create function auth.jwt()
returns jsonb
language sql
stable
as $$
  select coalesce(
    nullif(current_setting('request.jwt.claims', true), '')::jsonb,
    '{}'::jsonb
  );
$$;

create function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(auth.jwt() ->> 'sub', '')::uuid;
$$;

grant usage on schema auth, public to authenticated;
grant execute on function auth.jwt(), auth.uid() to authenticated;

create table public.organizations (
  id uuid primary key default extensions.gen_random_uuid(),
  name text not null
);

create table public.user_roles (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  organization_id uuid references public.organizations(id) on delete restrict,
  role public.app_role not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table public.owners (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  email text,
  phone text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.properties_v2 (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  owner_id uuid not null references public.owners(id) on delete restrict,
  name text not null,
  address_line text not null,
  city text,
  postal_code text,
  country_code text not null default 'ES',
  status public.property_status not null default 'onboarding',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.rooms_v2 (
  id uuid primary key default extensions.gen_random_uuid(),
  property_id uuid not null references public.properties_v2(id) on delete restrict,
  label text not null,
  description text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  unique (property_id, label)
);

create table public.occupancies_v2 (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  property_id uuid not null references public.properties_v2(id) on delete restrict,
  room_id uuid not null references public.rooms_v2(id) on delete restrict,
  occupant_email text not null,
  starts_on date not null,
  ends_on date,
  status public.record_status not null default 'active',
  user_id uuid references auth.users(id) on delete restrict
);

create table public.audit_log_v2 (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.organizations(id),
  actor_user_id uuid references auth.users(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  result text not null default 'success',
  details jsonb,
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on table public.owners to anon, authenticated;

alter table public.owners enable row level security;

create policy owners_read_scope
on public.owners
for select
to authenticated
using (
  user_id = (select auth.uid())
  or ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'root'
  or (
    organization_id::text = ((select auth.jwt()) -> 'app_metadata' ->> 'organization_id')
    and ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
  )
);

create function public.prevent_root_role_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (tg_op = 'DELETE' and old.role = 'root')
     or (tg_op = 'UPDATE' and old.role = 'root'
         and (new.role is distinct from old.role
              or new.user_id is distinct from old.user_id
              or new.revoked_at is distinct from old.revoked_at)) then
    raise exception 'ROOT role is immutable';
  end if;
  return coalesce(new, old);
end;
$$;

create trigger trg_protect_root_role
before update or delete on public.user_roles
for each row execute function public.prevent_root_role_mutation();

with fixture as (
  select
    extensions.gen_random_uuid() as organization_id,
    extensions.gen_random_uuid() as root_user_id
)
insert into public.organizations (id, name)
select organization_id, 'Allaiso' from fixture
returning id \gset allaiso_

insert into auth.users (id)
values (extensions.gen_random_uuid())
returning id \gset root_

insert into public.user_roles (user_id, organization_id, role)
values (:'root_id', :'allaiso_id', 'root');
