-- Reproducible baseline for the pre-tracked remote schema.
-- No production data or auth users are copied.
-- This file intentionally precedes all incremental migrations in Git.

create schema if not exists private;
create schema if not exists extensions;

do $$ begin
  create type public.record_status as enum ('active', 'blocked', 'archived');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.property_status as enum (
    'onboarding', 'active', 'maintenance', 'blocked', 'offboarding', 'archived'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.app_role as enum ('root', 'admin', 'owner', 'employee', 'tenant');
exception when duplicate_object then null; end $$;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null
);

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  organization_id uuid references public.organizations(id) on delete restrict,
  role public.app_role not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.owners (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  email text,
  phone text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table if not exists public.properties_v2 (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  owner_id uuid not null references public.owners(id) on delete restrict,
  name text not null,
  address_line text not null,
  city text,
  postal_code text,
  country_code text not null default 'ES',
  status public.property_status not null default 'onboarding',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table if not exists public.rooms_v2 (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties_v2(id) on delete restrict,
  label text not null,
  description text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  unique (property_id, label)
);

create table if not exists public.occupancies_v2 (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  property_id uuid not null references public.properties_v2(id) on delete restrict,
  room_id uuid not null references public.rooms_v2(id) on delete restrict,
  occupant_email text not null,
  starts_on date not null,
  ends_on date,
  status public.record_status not null default 'active',
  user_id uuid references auth.users(id) on delete restrict
);

create table if not exists public.property_staff_access_v3 (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  property_id uuid not null references public.properties_v2(id) on delete restrict,
  employee_user_id uuid not null references auth.users(id) on delete restrict,
  assignment_type text not null
    check (assignment_type in ('responsible','access','delegate','reader')),
  can_write boolean not null default false,
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  check (valid_until is null or valid_until > valid_from)
);

create table if not exists public.audit_log_v2 (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.organizations(id),
  actor_user_id uuid references auth.users(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  result text not null default 'success',
  details jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.incidents_v2 (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  property_id uuid not null references public.properties_v2(id),
  room_id uuid references public.rooms_v2(id),
  created_by uuid not null references auth.users(id),
  assigned_to uuid references auth.users(id),
  category text not null,
  description text not null,
  priority text not null default 'normal'
    check (priority in ('low','normal','high','urgent')),
  status text not null default 'reported'
    check (status in ('reported','triaged','assigned','in_progress','resolved','closed','rejected','reopened')),
  rejection_reason text,
  resolved_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incident_updates_v2 (
  id uuid primary key default gen_random_uuid(),
  incident_id uuid not null references public.incidents_v2(id),
  author_user_id uuid not null references auth.users(id),
  visibility text not null check (visibility in ('tenant','internal','owner')),
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.incident_evidence_v2 (
  id uuid primary key default gen_random_uuid(),
  incident_id uuid not null references public.incidents_v2(id),
  uploaded_by uuid not null references auth.users(id),
  visibility text not null default 'internal'
    check (visibility in ('tenant','internal','owner')),
  evidence_type text not null default 'photo',
  storage_path text not null,
  content_sha256 text,
  created_at timestamptz not null default now()
);

create table if not exists public.cleaning_plans_v2 (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  property_id uuid not null references public.properties_v2(id),
  name text not null,
  cadence text not null default 'weekly',
  active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cleaning_tasks_v2 (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  property_id uuid not null references public.properties_v2(id),
  room_id uuid references public.rooms_v2(id),
  plan_id uuid references public.cleaning_plans_v2(id),
  assigned_user_id uuid references auth.users(id),
  task_date date not null,
  status text not null default 'pending'
    check (status in ('pending','accepted','in_progress','submitted','approved','rejected','swapped','missed','cancelled')),
  verification_mode text not null default 'manual'
    check (verification_mode in ('manual','ai','hybrid')),
  submitted_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cleaning_swap_requests_v2 (
  id uuid primary key default gen_random_uuid(),
  cleaning_task_id uuid not null references public.cleaning_tasks_v2(id),
  requester_user_id uuid not null references auth.users(id),
  target_user_id uuid not null references auth.users(id),
  status text not null default 'pending'
    check (status in ('pending','accepted','rejected','cancelled')),
  requested_at timestamptz not null default now(),
  decided_at timestamptz
);

create table if not exists public.cleaning_debts_v2 (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  property_id uuid not null references public.properties_v2(id),
  debtor_user_id uuid not null references auth.users(id),
  creditor_user_id uuid not null references auth.users(id),
  source_task_id uuid references public.cleaning_tasks_v2(id),
  amount integer not null default 1 check (amount > 0),
  status text not null default 'open'
    check (status in ('open','settled','cancelled')),
  created_at timestamptz not null default now(),
  settled_at timestamptz
);

alter table public.owners enable row level security;
alter table public.incidents_v2 enable row level security;
alter table public.incident_updates_v2 enable row level security;
alter table public.incident_evidence_v2 enable row level security;
alter table public.cleaning_plans_v2 enable row level security;
alter table public.cleaning_tasks_v2 enable row level security;
alter table public.cleaning_swap_requests_v2 enable row level security;
alter table public.cleaning_debts_v2 enable row level security;

do $$ begin
  create policy owners_read_scope on public.owners
  for select to authenticated
  using (
    user_id = (select auth.uid())
    or ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'root'
    or (
      organization_id::text = ((select auth.jwt()) -> 'app_metadata' ->> 'organization_id')
      and ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
    )
  );
exception when duplicate_object then null; end $$;

create or replace function public.prevent_root_role_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (tg_op = 'DELETE' and old.role = 'root')
     or (tg_op = 'UPDATE' and old.role = 'root'
         and (new.role is distinct from old.role
              or new.user_id is distinct from old.user_id
              or new.revoked_at is distinct from old.revoked_at)) then
    raise exception 'ROOT role is immutable';
  end if;
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_protect_root_role on public.user_roles;
create trigger trg_protect_root_role
before update or delete on public.user_roles
for each row execute function public.prevent_root_role_mutation();

do $$ begin
  create policy incidents_root_admin_read on public.incidents_v2
  for select to authenticated
  using (
    ((select auth.jwt())->'app_metadata'->>'role')='root'
    or (
      ((select auth.jwt())->'app_metadata'->>'role')='admin'
      and organization_id::text=((select auth.jwt())->'app_metadata'->>'organization_id')
    )
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy incident_updates_root_admin_read on public.incident_updates_v2
  for select to authenticated
  using (
    exists (
      select 1 from public.incidents_v2 i
      where i.id=incident_id
      and (
        ((select auth.jwt())->'app_metadata'->>'role')='root'
        or (
          ((select auth.jwt())->'app_metadata'->>'role')='admin'
          and i.organization_id::text=((select auth.jwt())->'app_metadata'->>'organization_id')
        )
      )
    )
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy incident_evidence_root_admin_read on public.incident_evidence_v2
  for select to authenticated
  using (
    exists (
      select 1 from public.incidents_v2 i
      where i.id=incident_id
      and (
        ((select auth.jwt())->'app_metadata'->>'role')='root'
        or (
          ((select auth.jwt())->'app_metadata'->>'role')='admin'
          and i.organization_id::text=((select auth.jwt())->'app_metadata'->>'organization_id')
        )
      )
    )
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy cleaning_plans_root_admin_read on public.cleaning_plans_v2
  for select to authenticated
  using (
    ((select auth.jwt())->'app_metadata'->>'role')='root'
    or (
      ((select auth.jwt())->'app_metadata'->>'role')='admin'
      and organization_id::text=((select auth.jwt())->'app_metadata'->>'organization_id')
    )
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy cleaning_tasks_root_admin_read on public.cleaning_tasks_v2
  for select to authenticated
  using (
    ((select auth.jwt())->'app_metadata'->>'role')='root'
    or (
      ((select auth.jwt())->'app_metadata'->>'role')='admin'
      and organization_id::text=((select auth.jwt())->'app_metadata'->>'organization_id')
    )
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy cleaning_debts_root_admin_read on public.cleaning_debts_v2
  for select to authenticated
  using (
    ((select auth.jwt())->'app_metadata'->>'role')='root'
    or (
      ((select auth.jwt())->'app_metadata'->>'role')='admin'
      and organization_id::text=((select auth.jwt())->'app_metadata'->>'organization_id')
    )
  );
exception when duplicate_object then null; end $$;
