-- GestionPisos · Flujos de Trabajo · ejecución manual idempotente
-- Este incremento crea ejecuciones y su evento inicial. NO crea todavía tareas ni recurrencias.

alter table public.workflow_applications_v2
  add constraint workflow_applications_v2_execution_identity_unique
  unique (id, definition_id, definition_version_id, organization_id);

create table public.workflow_executions_v2 (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null,
  definition_id uuid not null,
  definition_version_id uuid not null,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  scope_type text not null check (scope_type in ('organization','property','room','occupancy')),
  property_id uuid references public.properties_v2(id) on delete restrict,
  room_id uuid references public.rooms_v2(id) on delete restrict,
  occupancy_id uuid references public.occupancies_v2(id) on delete restrict,
  trigger_kind text not null check (trigger_kind in ('manual_now')),
  idempotency_key text not null check (
    length(btrim(idempotency_key)) between 1 and 200
  ),
  assignment_type text not null check (
    assignment_type in ('property_responsible','active_occupants_rotation','fixed_person','role','manual')
  ),
  assigned_user_id uuid not null references auth.users(id) on delete restrict,
  status text not null default 'pending' check (
    status in ('pending','active','waiting_review','completed','cancelled','failed')
  ),
  spec_snapshot jsonb not null,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  constraint workflow_executions_v2_application_identity_fkey
    foreign key (application_id,definition_id,definition_version_id,organization_id)
    references public.workflow_applications_v2(id,definition_id,definition_version_id,organization_id)
    on delete restrict,
  constraint workflow_executions_v2_scope_shape_check check (
    (scope_type='organization' and property_id is null and room_id is null and occupancy_id is null)
    or
    (scope_type='property' and property_id is not null and room_id is null and occupancy_id is null)
    or
    (scope_type='room' and property_id is not null and room_id is not null and occupancy_id is null)
    or
    (scope_type='occupancy' and property_id is not null and room_id is null and occupancy_id is not null)
  )
);

create unique index workflow_executions_v2_application_idempotency_uq
  on public.workflow_executions_v2(application_id,idempotency_key);

create index workflow_executions_v2_org_created_idx
  on public.workflow_executions_v2(organization_id,created_at desc);

create index workflow_executions_v2_application_created_idx
  on public.workflow_executions_v2(application_id,created_at desc);

create index workflow_executions_v2_assigned_status_idx
  on public.workflow_executions_v2(assigned_user_id,status,created_at desc);

create table public.workflow_execution_events_v2 (
  id bigint generated by default as identity primary key,
  execution_id uuid not null references public.workflow_executions_v2(id) on delete restrict,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  event_type text not null check (length(btrim(event_type)) between 1 and 80),
  from_status text,
  to_status text,
  actor_user_id uuid references auth.users(id) on delete restrict,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index workflow_execution_events_v2_execution_created_idx
  on public.workflow_execution_events_v2(execution_id,created_at,id);

alter table public.workflow_executions_v2 enable row level security;
alter table public.workflow_execution_events_v2 enable row level security;

revoke all on public.workflow_executions_v2 from anon;
revoke all on public.workflow_execution_events_v2 from anon;
revoke insert,update,delete,truncate,references,trigger on public.workflow_executions_v2 from authenticated;
revoke insert,update,delete,truncate,references,trigger on public.workflow_execution_events_v2 from authenticated;
grant select on public.workflow_executions_v2 to authenticated;
grant select on public.workflow_execution_events_v2 to authenticated;

create policy workflow_executions_v2_read_authorized
on public.workflow_executions_v2
for select
to authenticated
using (
  assigned_user_id=auth.uid()
  or public.workflow_can_read_definitions_v1(organization_id)
  or (
    property_id is not null
    and public.can_operate_property_v3(property_id,false)
  )
);

create policy workflow_execution_events_v2_read_authorized
on public.workflow_execution_events_v2
for select
to authenticated
using (
  exists(
    select 1
    from public.workflow_executions_v2 e
    where e.id=execution_id
  )
);

create or replace function public.execute_workflow_application_now_v1(
  p_application_id uuid,
  p_idempotency_key text,
  p_assigned_user_id uuid default null
)
returns table(
  execution_id uuid,
  status text,
  assigned_user_id uuid,
  created_at timestamptz,
  created_new boolean
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_actor uuid:=auth.uid();
  v_definition_id uuid;
  v_version_id uuid;
  v_org uuid;
  v_scope_type text;
  v_property_id uuid;
  v_room_id uuid;
  v_occupancy_id uuid;
  v_application_status text;
  v_spec jsonb;
  v_assignment_type text;
  v_assigned_user uuid;
  v_execution_id uuid;
  v_execution_status text;
  v_execution_created_at timestamptz;
  v_key text:=nullif(btrim(p_idempotency_key),'');
  v_is_root boolean:=false;
  v_is_admin boolean:=false;
  v_can_launch boolean:=false;
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode='42501';
  end if;

  if v_key is null or length(v_key)>200 then
    raise exception 'workflow_idempotency_key_invalid' using errcode='22023';
  end if;

  select
    wa.definition_id,
    wa.definition_version_id,
    wa.organization_id,
    wa.scope_type,
    wa.property_id,
    wa.room_id,
    wa.occupancy_id,
    wa.status,
    wv.spec
  into
    v_definition_id,
    v_version_id,
    v_org,
    v_scope_type,
    v_property_id,
    v_room_id,
    v_occupancy_id,
    v_application_status,
    v_spec
  from public.workflow_applications_v2 wa
  join public.workflow_definition_versions_v2 wv
    on wv.id=wa.definition_version_id
   and wv.definition_id=wa.definition_id
   and wv.organization_id=wa.organization_id
  where wa.id=p_application_id
  for update of wa;

  if v_definition_id is null then
    raise exception 'workflow_application_not_found' using errcode='P0002';
  end if;

  if v_application_status<>'configured' then
    raise exception 'workflow_application_not_executable' using errcode='55000';
  end if;

  select exists(
    select 1 from public.user_roles ur
    where ur.user_id=v_actor
      and ur.role='root'
      and ur.revoked_at is null
  ) into v_is_root;

  select exists(
    select 1 from public.user_roles ur
    where ur.user_id=v_actor
      and ur.organization_id=v_org
      and ur.role='admin'
      and ur.revoked_at is null
  ) into v_is_admin;

  v_can_launch:=v_is_root or v_is_admin;

  if not v_can_launch and v_property_id is not null then
    v_can_launch:=public.can_operate_property_v3(v_property_id,true);
  end if;

  if not v_can_launch then
    raise exception 'workflow_execution_not_authorized' using errcode='42501';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_application_id::text||':execute:'||v_key,0)
  );

  select e.id,e.status,e.assigned_user_id,e.created_at
  into v_execution_id,v_execution_status,v_assigned_user,v_execution_created_at
  from public.workflow_executions_v2 e
  where e.application_id=p_application_id
    and e.idempotency_key=v_key;

  if v_execution_id is not null then
    return query
    select v_execution_id,v_execution_status,v_assigned_user,v_execution_created_at,false;
    return;
  end if;

  -- Revalidar el destino real en el momento de ejecutar.
  if v_scope_type='property' then
    if not exists(
      select 1 from public.properties_v2 p
      where p.id=v_property_id
        and p.organization_id=v_org
        and p.archived_at is null
        and p.status<>'archived'
    ) then
      raise exception 'workflow_execution_property_unavailable' using errcode='55000';
    end if;
  elsif v_scope_type='room' then
    if not exists(
      select 1
      from public.rooms_v2 r
      join public.properties_v2 p on p.id=r.property_id
      where r.id=v_room_id
        and r.property_id=v_property_id
        and p.organization_id=v_org
        and p.archived_at is null
        and p.status<>'archived'
        and r.archived_at is null
        and r.status<>'archived'
    ) then
      raise exception 'workflow_execution_room_unavailable' using errcode='55000';
    end if;
  elsif v_scope_type='occupancy' then
    if not exists(
      select 1
      from public.occupancies_v2 o
      join public.properties_v2 p on p.id=o.property_id
      where o.id=v_occupancy_id
        and o.organization_id=v_org
        and o.property_id=v_property_id
        and p.organization_id=v_org
        and p.archived_at is null
        and p.status<>'archived'
        and o.status='active'
        and o.starts_on<=current_date
        and (o.ends_on is null or o.ends_on>=current_date)
    ) then
      raise exception 'workflow_execution_occupancy_unavailable' using errcode='55000';
    end if;
  elsif v_scope_type<>'organization' then
    raise exception 'workflow_scope_invalid' using errcode='22023';
  end if;

  v_assignment_type:=nullif(v_spec->>'assignmentType','');

  if v_assignment_type='manual' then
    if p_assigned_user_id is null then
      raise exception 'workflow_manual_assignee_required' using errcode='22023';
    end if;

    if exists(
      select 1 from public.user_roles ur
      where ur.user_id=p_assigned_user_id
        and ur.role='root'
        and ur.revoked_at is null
    ) then
      v_assigned_user:=p_assigned_user_id;
    elsif exists(
      select 1 from public.user_roles ur
      where ur.user_id=p_assigned_user_id
        and ur.organization_id=v_org
        and ur.role='admin'
        and ur.revoked_at is null
    ) then
      v_assigned_user:=p_assigned_user_id;
    elsif exists(
      select 1 from public.user_roles ur
      where ur.user_id=p_assigned_user_id
        and ur.organization_id=v_org
        and ur.role='employee'
        and ur.revoked_at is null
    ) and (
      v_property_id is null
      or exists(
        select 1
        from public.property_staff_access_v3 a
        where a.property_id=v_property_id
          and a.employee_user_id=p_assigned_user_id
          and a.revoked_at is null
          and (a.valid_until is null or a.valid_until>now())
          and a.can_write=true
          and a.assignment_type in ('responsible','access')
      )
    ) then
      v_assigned_user:=p_assigned_user_id;
    else
      raise exception 'workflow_manual_assignee_not_eligible' using errcode='42501';
    end if;
  elsif v_assignment_type='property_responsible' then
    if p_assigned_user_id is not null then
      raise exception 'workflow_assignee_must_be_server_resolved' using errcode='22023';
    end if;

    if v_property_id is null then
      raise exception 'workflow_property_responsible_scope_required' using errcode='22023';
    end if;

    select a.employee_user_id
    into v_assigned_user
    from public.property_staff_access_v3 a
    join public.user_roles ur
      on ur.user_id=a.employee_user_id
     and ur.organization_id=v_org
     and ur.role in ('employee','admin')
     and ur.revoked_at is null
    where a.property_id=v_property_id
      and a.assignment_type='responsible'
      and a.revoked_at is null
      and (a.valid_until is null or a.valid_until>now())
      and a.can_write=true
    limit 1;

    if v_assigned_user is null then
      raise exception 'workflow_property_responsible_unavailable' using errcode='55000';
    end if;
  elsif v_assignment_type in ('fixed_person','role','active_occupants_rotation') then
    raise exception 'workflow_assignment_not_supported' using errcode='0A000';
  else
    raise exception 'workflow_assignment_invalid' using errcode='22023';
  end if;

  insert into public.workflow_executions_v2(
    application_id,definition_id,definition_version_id,organization_id,
    scope_type,property_id,room_id,occupancy_id,
    trigger_kind,idempotency_key,assignment_type,assigned_user_id,
    status,spec_snapshot,created_by
  ) values (
    p_application_id,v_definition_id,v_version_id,v_org,
    v_scope_type,v_property_id,v_room_id,v_occupancy_id,
    'manual_now',v_key,v_assignment_type,v_assigned_user,
    'pending',v_spec,v_actor
  )
  returning id,status,created_at
  into v_execution_id,v_execution_status,v_execution_created_at;

  insert into public.workflow_execution_events_v2(
    execution_id,organization_id,event_type,from_status,to_status,actor_user_id,details
  ) values (
    v_execution_id,v_org,'created',null,'pending',v_actor,
    jsonb_build_object(
      'trigger_kind','manual_now',
      'assignment_type',v_assignment_type,
      'assigned_user_id',v_assigned_user,
      'application_id',p_application_id,
      'definition_version_id',v_version_id
    )
  );

  insert into public.audit_log_v2(
    organization_id,actor_user_id,action,entity_type,entity_id,result,details
  ) values (
    v_org,v_actor,'workflow_execution_created','workflow_execution',
    v_execution_id::text,'success',
    jsonb_build_object(
      'application_id',p_application_id,
      'definition_id',v_definition_id,
      'definition_version_id',v_version_id,
      'scope_type',v_scope_type,
      'property_id',v_property_id,
      'room_id',v_room_id,
      'occupancy_id',v_occupancy_id,
      'assignment_type',v_assignment_type,
      'assigned_user_id',v_assigned_user,
      'idempotency_key',v_key
    )
  );

  return query
  select v_execution_id,v_execution_status,v_assigned_user,v_execution_created_at,true;
end;
$$;

revoke all on function public.execute_workflow_application_now_v1(uuid,text,uuid) from public;
revoke execute on function public.execute_workflow_application_now_v1(uuid,text,uuid) from anon;
grant execute on function public.execute_workflow_application_now_v1(uuid,text,uuid) to authenticated;

comment on table public.workflow_executions_v2 is
  'Ejecución concreta e inmutable en identidad de una aplicación/version. Este incremento solo crea estado pending mediante manual_now.';
comment on table public.workflow_execution_events_v2 is
  'Historial funcional mínimo de ejecuciones. No sustituye audit_log_v2.';
comment on function public.execute_workflow_application_now_v1(uuid,text,uuid) is
  'Crea de forma idempotente una ejecución manual_now, revalida ámbito y congela la asignación. No materializa todavía tenant_tasks_v2.';
